### ISSUE TITLE
Environment Server

### ISSUE THREAD

**Issue by Aslan15** [seakers/DMASpy#2]
Class in charge of setting up a server where agent nodes in the DMAS network can request information from and obtain data and insight into the state of the environment that they live in.

**ToDo's**

_Server Features_ 
- [x] Broadcast and Req-Res port setup
- [x] Internal Request Handler (forwards internal messages to the appropriate submodules)
- [x] Broadcast Request Handler (schedules broadcasts to all agent nodes)
- [x] External Request Handler (forwards external requests messages to the appropriate submodules)

_Event Broadcasting_
The environment broadcasts to agents whenever an event starts or ends. These announcements are left to the agent nodes to react to as they see fit.
- [x] Eclipse Events
- [x] Ground Station Access Events
- [x] Agent Access Events
- [ ] Ground Point Access Events

_Agent Requests_
Answer to requests sent by an agent. These requests might require an immediate response or may require the environment server to schedule a future event broadcast.
- [x] tic_request: agents ask to be notified when a certain time has passed in the environment's clock    
- [ ] agent_access_request: agent asks the environment if the agent is capable of accessing another agent at the current simulation time
- [ ] gp_access_request: agent asks the environment if the agent is capable of accessing a ground point at the current simulation time
- [ ] gs_access_request: agent asks the environment if the agent is capable of accessing a ground station at the current simulation time
- [ ] agent_information_request: agent asks for information regarding its current position, velocity, and eclipse at the current simulation time
- [ ] observation_request: agent requests environment information regarding a the state of a ground point at the current simulation time
- [ ] agent_end_confirmation: agent notifies the environment that it has successfully terminated its operations

_Simulation_
- [x] simulation start broadcast
- [x] simulation time broadcast
- [ ] simulation end broadcast
